player: Maeby
server: Mischief
log_parsing:
  enabled: true
  cycle_on_start: false
guild_dumps:
  enabled: true
  interval_min: 300
  interval_max: 600
game:
  root_folder: C:\Program Files (x86)\Steam\steamapps\common\Everquest F2P
